app:
  get_started:
    title: Введение

mods:
  navigation: { version: 0.1.0, src: '..\mods\src' }
  footer: { version: 0.1.0, src: '..\mods\src' }

mod:
  footer:
    copyright: Taskurotta Team 2013 Введение
    links:
      - id: footnav_blog
        href: 'https://github.com/taskurotta/taskurotta.org'
        name: Blog
      - id: footnav_issue
        href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
        name: Issues
