app:
  road_map:
    # Page params
    title: План
    mods:
      - name: app
        version: 0.1.0
      - name: markdown
        version: 0.1.0
      - name:  navigation
        version: 0.1.0
      - name:  footer
        version: 0.1.0
