app:
  name: documentation
  title: Документация

mod:
  footer:
    copyright: Taskurotta Team 2013
    links:
      - id: footnav_blog
        href: 'https://github.com/taskurotta/taskurotta'
        name: Source
      - id: footnav_issue
        href: 'https://github.com/taskurotta/taskurotta/issues?page=1&state=open'
        name: Issues