title: Taskurotta
version: 0.1.0
#base
apps:
  index: { src: '../apps/src', template: 'base' }
  get_started: { src: '../apps/src', template: 'base' }
  road_map: { src: '../apps/src', template: 'base' }
mods:
  core: { version: 0.1.0, src: '../mod_core/src' }
  markdown: { version: 0.1.0, src: '../mods/src' }
  navigation: { version: 0.1.0, src: '../mods/src' }
  footer: { version: 0.1.0, src: '../mods/src' }
libs:
  html5shiv: { file: dist/html5shiv.js, src: 'bower_components' }
  jquery: { file: jquery.js, src: 'bower_components' }
  angular: { file: angular.js, src: 'bower_components' }
  angular-ui-router: { file: release/angular-ui-router.js, src: 'bower_components' }
  showdown: { file: compressed/showdown.js, src: 'bower_components' }
  bootstrap: { file: dist/js/bootstrap.js, src: 'bower_components' }

#portal theme
template: { name: base, src: '../template/src' }
#individual
mod:
  navigation:
    search: true
    menu:
      dropdown: true
      items:
         - { id: rootnav_index, href: index.html, name: Taskurotta }
         - { id: rootnav_get_started, href: get_started.html, name: Введение }
         - { id: rootnav_road_map,  href: road_map.html, name: План }
         - id: rootnav_doc
           href: '#'
           name: Документация (TODO)
           items:
              - { id: 1, href: '#', name: Основная концепция }
              - { id: 2, href: '#', name: Сценарии использования }
              - { id: 3, delim: true, href: '#', name: Пакеты }
              - { id: 4, href: '#', name: Аннотации }
              - { id: 5, href: '#', name: Исключения }
              - { id: 6, href: '#', name: Мониторинг }
              - { id: 7, delim: true, href: '#', name: Unit тесты }
              - { id: 8, href: '#', name: Регрессионное тестирование }
              - { id: 9, href: '#', name: A/B тестирование }
  footer:
    copyright: Taskurotta Team 2013
    links:
      - id: footnav_blog
        href: 'https://github.com/taskurotta/taskurotta.org'
        name: Blog
      - id: footnav_issue
        href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
        name: Issues
  markdown:
    path: '/md'
