indexApp:
    # Page params
    layout: home.hbs
    title: Введение
    app: index
    mods:
      - name: app
        version: 0.1.0
      - name: markdown
        version: 0.1.0
      - name:  navigation
        version: 0.1.0
      - name:  footer
        version: 0.1.0