title: Taskurotta
version: 0.1.0
mod:
  navigation:
    search: true
    menu:
      dropdown: true
      items:
         - { id: rootnav_index, href: index.html, name: Taskurotta }
         - { id: rootnav_get_started, href: get_started.html, name: Введение }
         - { id: rootnav_road_map,  href: road_map.html, name: План }
         - id: rootnav_doc
           href: '#'
           name: Документация (TODO)
           items:
              - { id: 1, href: '#', name: Основная концепция }
              - { id: 2, href: '#', name: Сценарии использования }
              - { id: 3, delim: true, href: '#', name: Пакеты }
              - { id: 4, href: '#', name: Аннотации }
              - { id: 5, href: '#', name: Исключения }
              - { id: 6, href: '#', name: Мониторинг }
              - { id: 7, delim: true, href: '#', name: Unit тесты }
              - { id: 8, href: '#', name: Регрессионное тестирование }
              - { id: 9, href: '#', name: A/B тестирование }
  footer:
    copyright: Taskurotta Team 2013
    links:
      - id: footnav_blog
        href: 'https://github.com/taskurotta/taskurotta.org'
        name: Blog
      - id: footnav_issue
        href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
        name: Issues
    0.1.0:
        copyright: Taskurotta Team 2013 0.1.0
        links:
          - id: footnav_blog
            href: 'https://github.com/taskurotta/taskurotta.org'
            name: Blog
          - id: footnav_issue
            href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
            name: Issues
  markdown:
    path: '/md'
