title: Taskurotta
version: 0.1.0
mod:
  navigation:
    search: true
    menu:
      dropdown: true
      items:
         - { id: rootnav_index, href: index.html, name: Taskurotta }
         - { id: rootnav_get_started, href: get_started.html, name: Введение }
         - { id: rootnav_road_map,  href: road_map.html, name: План }
         - id: rootnav_documetation
           href: '#'
           name: Документация
           items:
              - { id: 1, href: 'documentation.html', name: Введение }
              - { id: 2, href: '#', name: Глава 1 }
  footer:
    copyright: Taskurotta Team 2013
    links:
      - id: footnav_blog
        href: 'https://github.com/taskurotta/taskurotta.org'
        name: Blog
      - id: footnav_issue
        href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
        name: Issues
    0.1.0:
        copyright: Taskurotta Team 2013 0.1.0
        links:
          - id: footnav_blog
            href: 'https://github.com/taskurotta/taskurotta.org'
            name: Blog
          - id: footnav_issue
            href: 'https://github.com/taskurotta/taskurotta.org/issues?state=open'
            name: Issues
  markdown:
    path: '/md'
